import '../styles/globals.css'
import JaponLogo from '@/components/japonLogo'
import NavigationBar from '@/components/navigationBar'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<JaponLogo />
				<NavigationBar />
				<div>{children}</div>
			</body>
		</html>
	)
}
